apiVersion: 1
contactPoints:
  - orgId: 1
    name: SMTP Email
    receivers:
      - uid: smtp-default
        type: email
        settings:
          addresses: ${GF_ALERT_EMAIL_TO}
          singleEmail: true
          subject: '[EPOP][${ENVIRONMENT}] ${ALERT_TITLE}'
          message: |
            ${ALERT_DESCRIPTION}

            Rule: ${RULE_NAME}
            State: ${ALERT_STATE}
            Firing: ${NUM_FIRING}
            Resolved: ${NUM_RESOLVED}

            Link: ${ALERT_URL}
        disableResolveMessage: false
