apiVersion: 1
policies:
  - orgId: 1
    receiver: SMTP Email
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: SMTP Email
        object_matchers:
          - [ severity, =, critical ]
        continue: true
      - receiver: SMTP Email
        object_matchers:
          - [ severity, =, warning ]
        continue: true
